### ISSUE TITLE
Поддержка новой ноды 16+

### ISSUE THREAD

**Issue by erhosen** [OXAYAZA/oxyz-build#1]
Сейчас невозможно установить пакет oxyz-build на новую ноду, так как она тянет в зависимостях древнючий node-sass

Я только недавно зашёл в мир js / npm / gulp / etc и честно немного в шоке от числа зависимостей и всего того бардака что у вас тут твориться. 

Это не к автору претензия, а просто крик души, сорри

**Comment by OXAYAZA** [comment]
Fixed in version 1.2.3
